export const ADD_COMPILATION_CHALLENGE = 'ADD_COMPILATION_CHALLENGE';
export const MODIFY_COMPILATION_CHALLENGE = 'MODIFY_COMPILATION_CHALLENGE';

export const ADD_TEST_CHALLENGE = 'ADD_TEST_CHALLENGE';
export const MODIFY_TEST_CHALLENGE = 'MODIFY_TEST_CHALLENGE';

export const DELETE_CHALLENGE = 'DELETE_CHALLENGE';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const FETCH_ALL_COMPILATION_CHALLENGE_REQUEST = 'FETCH_ALL_COMPILATION_CHALLENGE_REQUEST';
export const FETCH_ALL_COMPILATION_CHALLENGE_SUCCESS = 'FETCH_ALL_COMPILATION_CHALLENGE_SUCCESS';
export const FETCH_ALL_COMPILATION_CHALLENGE_FAILURE = 'FETCH_ALL_COMPILATION_CHALLENGE_FAILURE';

export const FETCH_ALL_TEST_CHALLENGE_REQUEST = 'FETCH_ALL_TEST_CHALLENGE_REQUEST';
export const FETCH_ALL_TEST_CHALLENGE_SUCCESS = 'FETCH_ALL_TEST_CHALLENGE_SUCCESS';
export const FETCH_ALL_TEST_CHALLENGE_FAILURE = 'FETCH_ALL_TEST_CHALLENGE_FAILURE';

export const FETCH_RESOLVED_COMPILATION_CHALLENGE_REQUEST = 'FETCH_RESOLVED_COMPILATION_CHALLENGE_REQUEST';
export const FETCH_RESOLVED_COMPILATION_CHALLENGE_SUCCESS = 'FETCH_RESOLVED_COMPILATION_CHALLENGE_SUCCESS';
export const FETCH_RESOLVED_COMPILATION_CHALLENGE_FAILURE = 'FETCH_RESOLVED_COMPILATION_CHALLENGE_FAILURE';

export const FETCH_RESOLVED_TEST_CHALLENGE_REQUEST = 'FETCH_RESOLVED_TEST_CHALLENGE_REQUEST';
export const FETCH_RESOLVED_TEST_CHALLENGE_SUCCESS = 'FETCH_RESOLVED_TEST_CHALLENGE_SUCCESS';
export const FETCH_RESOLVED_TEST_CHALLENGE_FAILURE = 'FETCH_RESOLVED_TEST_CHALLENGE_FAILURE';

export const FETCH_UNSOLVED_COMPILATION_CHALLENGE_REQUEST = 'FETCH_UNSOLVED_COMPILATION_CHALLENGE_REQUEST';
export const FETCH_UNSOLVED_COMPILATION_CHALLENGE_SUCCESS = 'FETCH_UNSOLVED_COMPILATION_CHALLENGE_SUCCESS';
export const FETCH_UNSOLVED_COMPILATION_CHALLENGE_FAILURE = 'FETCH_UNSOLVED_COMPILATION_CHALLENGE_FAILURE';

export const FETCH_UNSOLVED_TEST_CHALLENGE_REQUEST = 'FETCH_UNSOLVED_TEST_CHALLENGE_REQUEST';
export const FETCH_UNSOLVED_TEST_CHALLENGE_SUCCESS = 'FETCH_UNSOLVED_TEST_CHALLENGE_SUCCESS';
export const FETCH_UNSOLVED_TEST_CHALLENGE_FAILURE = 'FETCH_UNSOLVED_TEST_CHALLENGE_FAILURE';

export const FETCH_CHALLENGES_ASSOCIATED_TO_USER_REQUEST = 'FETCH_CHALLENGES_ASSOCIATED_TO_USER_REQUEST';
export const FETCH_CHALLENGES_ASSOCIATED_TO_USER_SUCCESS = 'FETCH_CHALLENGES_ASSOCIATED_TO_USER_SUCCESS';
export const FETCH_CHALLENGES_ASSOCIATED_TO_USER_FAILURE = 'FETCH_CHALLENGES_ASSOCIATED_TO_USER_FAILURE';
