export const ADD_HACKER = 'ADD_HACKER';
export const DELETE_HACKER = 'DELETE_HACKER';

export const FETCH_HACKER_REQUEST = 'FETCH_HACKER_REQUEST'
export const FETCH_HACKER_SUCCESS = 'FETCH_HACKER_SUCCESS'
export const FETCH_HACKER_FAILURE = 'FETCH_HACKER_FAILURE'

export const FETCH_HACKERS_REQUEST = 'FETCH_HACKERS_REQUEST'
export const FETCH_HACKERS_SUCCESS = 'FETCH_HACKERS_SUCCESS'
export const FETCH_HACKERS_FAILURE = 'FETCH_HACKERS_FAILURE'


export const FETCH_PROPOSITIONS_REQUEST = 'FETCH_PROPOSITIONS_REQUEST'
export const FETCH_PROPOSITIONS_SUCCESS = 'FETCH_PROPOSITIONS_SUCCESS'
export const FETCH_PROPOSITIONS_FAILURE = 'FETCH_PROPOSITIONS_FAILURE'






export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'

export const ADD_COMMENT = 'ADD_COMMENT'
export const FETCH_ADD_COMMENT_FAILURE = 'FETCH_ADD_COMMENTS_FAILURE'

export const ADD_RESPONSE = 'ADD_RESPONSE'
export const FETCH_ADD_RESPONSE_FAILURE ='FETCH_ADD_RESPONSE_FAILURE'

export const FETCH_RESPONSES_REQUEST = 'FETCH_RESPONSES_REQUEST'
export const FETCH_RESPONSES_SUCCESS = 'FETCH_RESPONSES_SUCCESS'
export const FETCH_RESPONSES_FAILURE = 'FETCH_RESPONSES_FAILURE'

