export const ADD_HACKER = 'ADD_HACKER';
export const DELETE_HACKER = 'DELETE_HACKER';

export const FETCH_HACKER_REQUEST = 'FETCH_HACKER_REQUEST'
export const FETCH_HACKER_SUCCESS = 'FETCH_HACKER_SUCCESS'
export const FETCH_HACKER_FAILURE = 'FETCH_HACKER_FAILURE'

export const FETCH_HACKERS_REQUEST = 'FETCH_HACKERS_REQUEST'
export const FETCH_HACKERS_SUCCESS = 'FETCH_HACKERS_SUCCESS'
export const FETCH_HACKERS_FAILURE = 'FETCH_HACKERS_FAILURE'

export const FETCH_PROPOSITIONS_REQUEST = 'FETCH_PROPOSITIONS_REQUEST'
export const FETCH_PROPOSITIONS_SUCCESS = 'FETCH_PROPOSITIONS_SUCCESS'
export const FETCH_PROPOSITIONS_FAILURE = 'FETCH_PROPOSITIONS_FAILURE'
