export const FETCH_RANKING_REQUEST = 'FETCH_RANKING_REQUEST';
export const FETCH_RANKING_SUCCESS = 'FETCH_RANKING_SUCESS';
export const FETCH_RANKING_FAILURE = 'FETCH_RANKING_FAILURE';
export const FETCH_INDIVIDUAL_STATS_REQUEST = 'FETCH_INDIVIDUAL_STATS_REQUEST';
export const FETCH_INDIVIDUAL_STATS_SUCCESS = 'FETCH_INDIVIDUAL_STATS_SUCCESS';
export const FETCH_INDIVIDUAL_STATS_FAILURE = 'FETCH_INDIVIDUAL_STATS_FAILURE';
