//export const ADD_CHALLENGESTAT = 'ADD_CHALLENGESTAT';
//export const DELETE_CHALLENGESTAT = 'DELETE_CHALLENGESTAT';

export const FETCH_CHALLENGESTAT_REQUEST = 'FETCH_CHALLENGESTAT_REQUEST'
export const FETCH_CHALLENGESTAT_SUCCESS = 'FETCH_CHALLENGESTAT_SUCCESS'
export const FETCH_CHALLENGESTAT_FAILURE = 'FETCH_CHALLENGESTAT_FAILURE'